# Generated by Django 3.2.13 on 2022-10-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_New2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('slug', models.SlugField(default='slug', max_length=150, unique=True)),
                ('photo', models.ImageField(upload_to='main_images/sports2')),
            ],
        ),
    ]
