# Generated by Django 3.2.13 on 2022-10-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_1', '0002_sport_new2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport_New2',
        ),
    ]
