# Generated by Django 3.2.13 on 2022-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_1', '0003_delete_sport_new2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_new',
            name='turi',
            field=models.CharField(default='turi', max_length=100),
        ),
    ]
