# Generated by Django 3.2.13 on 2022-10-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_1', '0007_alter_sport_new_turi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport_new',
            name='turi',
            field=models.CharField(default='turi', max_length=120),
        ),
    ]
